version: '3.3'
services:

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Nginx/core:/etc/nginx/conf.d
      - ./www:/var/www/
      - ./Nginx/Logs:/var/log/nginx/
      - ./Nginx/html:/usr/share/nginx/html/
    links:
      - php
    networks:
      - app-network

  php:
    build:
      context: ./PHP
      dockerfile: Dockerfile
      args:
        UID: ${UD:-1000}
        GID: ${GD:-1000}
    container_name: php
    volumes:
      - ./www:/var/www
    links:
      - mysql
    networks:
      - app-network

  mysql:
    image: mysql:latest
    ports:
    - "3306:3306"
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=db
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_USER=db_user
      - MYSQL_PASSWORD=password
    volumes:
      - ./MySQL:/var/lib/mysql
    networks:
      - app-network

#Networks
networks:
  app-network: